### ISSUE TITLE
Nice - a few suggestions to make it more general purpose

### ISSUE THREAD

**Issue by jesperordrup** [delay/sveltekit-auth#3]
If your goal is to make a cool start package for sveltekit with lucia auth then consider making it (even) more generally approachable

- [ ] skip aws ties - go with a simple nodenmailer config
- [ ] default to sqlite and remove the postgresql ties (roles and default values fro timevalues)

just my two cents :.-)

**Comment by ArmantG** [comment]
Yeah agree with above. Would also like to see the auth get updated to Lucia v3. Assuming we waiting for Svelte 5 to drop officially, can then update project to Svelte 5 and Lucia v3 same time...?

**Comment by delay** [comment]
I do use nodemailer to send.  I use to have a completely custom aws send routine.  I added nodemailer in so you just have to insert a standard config into nodemailer and it will work and remove AWS config and package. AWS is kind of hard to configure and it is the cheapest option for sending mail so I have it as an example of how to configure it.  To use a simpler setup do this:

REMOVE THIS email-send.ts
```
import nodemailer from 'nodemailer';
import * as aws from '@aws-sdk/client-ses';
import {
	FROM_EMAIL,
	AWS_ACCESS_KEY_ID,
	AWS_SECRET_ACCESS_KEY,
	AWS_REGION,
	AWS_API_VERSION
} from '$env/static/private';
//import { z } from "zod";
export default async function sendEmail(
	email: string,
	subject: string,
	bodyHtml?: string,
	bodyText?: string
) {
	const hasAccessKeys = AWS_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY;

	const ses = new aws.SES({
		apiVersion: AWS_API_VERSION,
		region: AWS_REGION,
		...(hasAccessKeys
			? {
					credentials: {
						accessKeyId: AWS_ACCESS_KEY_ID || '',
						secretAccessKey: AWS_SECRET_ACCESS_KEY || ''
					}
			  }
			: {})
	});

	// create Nodemailer SES transporter
	const transporter = nodemailer.createTransport({
		SES: { ses, aws }
	});

```
REPLACE WITH:
```
import nodemailer from 'nodemailer';
export default async function sendEmail(
	email: string,
	subject: string,
	bodyHtml?: string,
	bodyText?: string
) {
const transporter = nodemailer.createTransport({
  host: "smtp.example.com",
  port: 587,
  secure: false, // upgrade later with STARTTLS
  auth: {
    user: "username",
    pass: "password",
  },
});

```
I will not default to sqlite as I think most people doing a production app use something like postgres or mysql.  I have used all three and I find postgres the most full featured.  It is very easy to use whatever db you want with prisma though. https://www.prisma.io/docs/orm/overview/databases I do plan to update to Lucia 3 when I get some time. This is his third major version in 6 months and he keeps changing how it works and should be integrated.  He has done a lot of work on his package and I appreciate it, but I hope in future releases he doesn't require such extensive rewrites to use his package.  

I also may move to drizzle instead of prisma as many want to use this with edge functions and drizzle is much less resource intensive than Prisma for edge stuff.  The problem with drizzle is while it can use many DB's, some queries change depending on features the db supports.  I do plan to update to svelte 5 once it is production ready.  Right now it is not close as far as I know and there are A LOT of things that are not working correctly. I am building a rather large app currently and I wanted to just use svelte 5 to develop with, but there are just too many bugs. 

Thanks for the suggestions and hope this helps a bit.

**Comment by jesperordrup** [comment]
Thanks for response. Well it's your code. I'm just saying that if you want to make it so ppl can download, run, learn...

Yes it's easy to remove Aws. But again if you try to do something for general purpose it's a strange tie to deal with. Id make it 100% .env configurable and default it to dump mails to console 

Reason for sqlite over postgresql:

1) if your solution runs with sqlite, everybody can press play. And you can just switch to postgres without code changes.

2) sqlite is used in production 👍 


About Prisma, we moved to drizzle (joins, runtime engine size). Perfect if u speak sql. Haven't had any regrets

**Comment by delay** [comment]
I have updated to lucia 3.  There were a ton of changes required, so many that I decided to just go ahead and also convert to drizzle from prisma.  So now it uses drizzle for the ORM.
